url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Alexis Peters
email: info@alexispeters.de
description: "Technical IT-Consultant, Software-Engineer and Code-Fireman."


# Team names, titles and social links
people:
- name: Alexis Peters
  pic: 1
  position: Freelancing IT-Consultant
  social:
    - title: twitter
      url: https://twitter.com/AlexisPetersDev
    - title: linkedIn
      url: https://www.linkedin.com/in/alexis-peters-2242a9122/
    - title: stack-overflow
      url: https://stackoverflow.com/users/4279830/alexis-peters

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Brüningstr. 37
  - line: 21614 Buxtehude

# Build settings
markdown: kramdown
permalink: pretty