url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Alexis Peters
email: info@alexispeters.de
description: "Technical IT-Consultant, DevOps-Engineer, Software-Engineer and Code-Fireman."


# Team names, titles and social links
people:
- name: Alexis Peters
  pic: me
  position: technical IT- and DevOps Consultant
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AlexisPetersDev
  - title: linkedin
    url: https://www.linkedin.com/in/alexis-peters-2242a9122/
  - title: stack-overflow
    url: https://stackoverflow.com/users/4279830/alexis-peters
  - title: github
    url: https://github.com/BlckStar

# Postal address (add as many lines as necessary)
address:
  - line: Brüningstr. 37
  - line: 21614 Buxtehude

# Build settings
markdown: kramdown
permalink: pretty